site_name: super-sayan-token
docs_dir: md-build
site_dir: gh-pages
permalink: True
nav:
  - Home: README.md
  - API:
      - Contracts:
          - SuperSaiyanToken: out/SuperSaiyanToken.md
          - DFOERC20NFTWrapper: out/DFOERC20NFTWrapper.md
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
    - typescript
    - javascript
